[project]
name = "book"
version = "0.1.0"
description = "A Quarto book project"
authors = ["Author Name <author@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
quarto = ">=1.4.0"

[tasks]
preview = "quarto preview"
render = "quarto render"
clean = "rm -rf _book"
